format_version: 10
pipelines:
  lab-micro-service-goci-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      docker_name: mayur21486
    secure_variables:
      docker_pass: AES:OXYwkDeq7mdM6mA0DANz0g==:Ur6bWL/XYygLodGGfkOaaA==
    materials:
      git-d960c79:
        git: https://github.com/mayur21486/lab_micro_service.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - lint-and-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test-code:
            timeout: 0
            elastic_profile_id: lab-elastic-agent-profle2
            tasks:
            - exec:
                arguments:
                - -c
                - git clone https://github.com/mayur21486/lab_micro_service.git
                command: /bin/sh
                run_if: any
            - exec:
                arguments:
                - -c
                - /bin/ls index.html
                command: /bin/sh
                working_directory: lab_micro_service
                run_if: any
    - build-and-publish:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          build:
            timeout: 0
            elastic_profile_id: lab-elastic-agent-profle2
            tasks:
            - exec:
                arguments:
                - -c
                - docker build .
                command: sh
                run_if: passed
          Tag:
            timeout: 0
            elastic_profile_id: lab-elastic-agent-profle2
            tasks:
            - exec:
                arguments:
                - -c
                - docker tag mayur21486/ft-nginx:v5
                command: sh
                run_if: passed
          publish:
            timeout: 0
            elastic_profile_id: lab-elastic-agent-profle2
            artifacts:
            - external:
                id: test-image
                store_id: docker-hub-mayur
                configuration:
                  options:
                    BuildFile: ''
                    Tag: v${GO_PIPELINE_LABEL}
                    Image: mayur21486/ft-nginx
            tasks:
            - exec:
                arguments:
                - -c
                - docker login --username=$docker_name --password=$docker_pass
                command: sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker push mayur21486/ft-nginx:v1
                command: sh
                run_if: passed
