format_version: 10
pipelines:
  lab-micro-service-goci:
    group: defaultGroup
    label_template: ${git:7}
    lock_behavior: none
    display_order: -1
    environment_variables:
      docker_name: mayur21486
    secure_variables:
      docker_pass: AES:OXYwkDeq7mdM6mA0DANz0g==:Ur6bWL/XYygLodGGfkOaaA==
    materials:
      git-af7c25a:
        git: https://github.com/mayur21486/lab_micro_service.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - lint-and-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test-code:
            timeout: 0
            elastic_profile_id: lab-elastic-agent-profle2
            tasks:
            - exec:
                arguments:
                - -c
                - git clone https://github.com/mayur21486/lab_micro_service.git
                command: /bin/sh
                run_if: any
            - exec:
                arguments:
                - -c
                - /bin/ls index.html
                command: /bin/sh
                working_directory: lab_micro_service
                run_if: any
    - build-and-publish:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        environment_variables:
          docker_name_from_stage: mayur21486
        secure_variables:
          docker_pass_from_stage: AES:xxR/OOPJzFevyEghma7mGw==:2GhjFoOFLDD6G53Ha6QBSA==
        jobs:
          build:
            timeout: 0
            elastic_profile_id: lab-elastic-agent-profle2
            tasks:
            - exec:
                arguments:
                - -c
                - env
                command: sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker build . -t mayur21486/ft-nginx:v2
                command: sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker login --username=$SECRET_USERNAME --password=$SECRET_PASSWORD
                command: sh
                run_if: passed
            - exec:
                arguments:
                - -c
                - docker push mayur21486/ft-nginx:v1
                command: sh
                run_if: passed
